### PR TITLE
Add get_mut to collections to retrieve value(s) mutably.

### PR DESCRIPTION
**Pull request by vlovich**

### CODE REVIEW

**Comment by pmarks** [comment]
I think this is superseded by #30?

**Comment by pmarks** [comment]
maybe all these didn't get included in the other PR.

**Comment by vlovich** [comment]
Oh shoot. I had intended them to not share a history. Let me update.

**Comment by vlovich** [comment]
Just a formatting difference. This can be closed out. Sorry about the mixup on my end.

**Pull request closed without merging**
