### PR TITLE
Remove Vectors to spare space

### PR DESCRIPTION
**Pull request by Tockra**
Since mphf is a static hash function there is no need to hold dynmic growing vectors. 
You can replace the vectors throw BoxedSlices, which spares one usize each.

### CODE REVIEW

**Comment by k3yavi** [comment]
Oh nice ! I wasn't even aware of that, good to know ! Curious how much performance gain you say with the change ?

**Comment by Tockra** [comment]
> 
> 
> Oh nice ! I wasn't even aware of that, good to know ! Curious how much performance gain you say with the change ?

It reduces the static size of a hashmap (stack-size) from 48 Byte to 32 Byte. Further it reduces the heap storage (see following diagram):
[paper.pdf](https://github.com/10XGenomics/rust-boomphf/files/3757735/paper.pdf)
Second one is better to read
[paper.pdf](https://github.com/10XGenomics/rust-boomphf/files/3757751/paper.pdf)

(x axis is the key count (tested with u16), y axis is bit/element )


I didn't made a benchmark of the speed, but there it shouldnt realy change...

**Comment by pmarks** [comment]
@Tockra Interesting, I hadn't seen that trick before.  In all our uses of `Mphf`, the size of the data for vec/slice is much largerr than 16/24 bytes of stack space consumed by the BoxedSlice/Vec, and we create a handful of `Mphf`'s at most.  How many elements are you typically loading into the `Mphf`, and are you planning on creating a large number of distinct `Mphf`s?

**Comment by Tockra** [comment]
> @Tockra Interesting, I hadn't seen that trick before. In all our uses of `Mphf`, the size of the data for vec/slice is much largerr than 16/24 bytes of stack space consumed by the BoxedSlice/Vec, and we create a handful of `Mphf`'s at most. How many elements are you typically loading into the `Mphf`, and are you planning on creating a large number of distinct `Mphf`s?

I planning to use the mphf hash functions to hash `u16` keys. I will use a lot of hash functions in my data structure. At the moment with 2^29 input values there are millions of hash functions. 
There I need every byte I can get.

The huge problem is that the input data is ordered. So I can use binary search instead of the mphf hash function. 
I made some measures and saw that binary search is faster. But the binary search uses 20-16 bit/element which is worse for >170keys. That isn't cool :/

**Comment by TomKellyGenetics** [comment]
Reporting an error here as this PR seems to be causing the issue. The package compiles with default setting but this breaks the "serde" feature.

```
$ cargo build --features "serde"
   Compiling boomphf v0.5.2 (/Users/tom/Downloads/repos/rust-boomphf)
error[E0308]: mismatched types
  --> src/bitvector.rs:44:38
   |
44 | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
   |                                      ^^^^^^^^^ expected struct `std::vec::Vec`, found struct `std::boxed::Box`
   |
   = note: expected type `&std::vec::Vec<std::sync::atomic::AtomicUsize>`
              found type `&'__a std::boxed::Box<[std::sync::atomic::AtomicUsize]>`

error[E0308]: mismatched types
  --> src/bitvector.rs:44:49
   |
44 | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
   |                                                 ^^^^^^^^^^^
   |                                                 |
   |                                                 expected struct `std::boxed::Box`, found struct `std::vec::Vec`
   |                                                 in this macro invocation
   |
   = note: expected type `std::boxed::Box<[std::sync::atomic::AtomicUsize]>`
              found type `std::vec::Vec<std::sync::atomic::AtomicUsize>`

error[E0308]: mismatched types
  --> src/bitvector.rs:44:49
   |
44 | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
   |                                                 ^^^^^^^^^^^
   |                                                 |
   |                                                 expected struct `std::boxed::Box`, found struct `std::vec::Vec`
   |                                                 in this macro invocation
   |
   = note: expected type `std::boxed::Box<[std::sync::atomic::AtomicUsize]>`
              found type `std::vec::Vec<std::sync::atomic::AtomicUsize>`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `boomphf`.

To learn more, run the command again with --verbose.
```

**Comment by pmarks** [comment]
@TomKellyGenetics thanks for the report -- it's now fixed on master.

**Pull request merged**
